### ISSUE TITLE
Code of Conduct Issue

### ISSUE THREAD

**Issue by Narrev** [NevermoreFramework/Nevermore#10]
Examples of unacceptable behavior by participants include:
- The use of sexualized language or imagery and unwelcome sexual attention or advances

```>unwelcome sexual attention or advances```

![](https://image.prntscr.com/image/VUFBik9dQlqsxT65maZJUQ.png)

**Comment by devSparkle** [comment]
@Narrev thank you for the report. This clarity issue has been addressed.
