### ISSUE TITLE
Move Nevermore to GitFlow

### ISSUE THREAD

**Issue by devSparkle** [NevermoreFramework/Nevermore#2]
GitFlow is a list of rules to keep a repo’s history organized, and is used to make the release process, bug fixes, and feature creation easier. I feel these changes are necessary going forward, seeing as the Nevermore plugin is able to pull directly from the master branch.

In a repo that uses GitFlow, two branches will always be present: `master` (The version in production) and `develop` (The version currently in development for the next release).

## Feature

Feature branches are used to develop new features for new releases and can also be used for bug fixes as well. They typically exist only in forks / local repos and aren't shared with others, but may be created here.

## Release

Releases are major and minor versions of your product that would be pushed to production. They're often within this main repository and shared with people that are working on the same version.

## Hotfix

Hotfixes are exactly the same as Releases in GitFlow, except hotfixes branches are created on top of `master`, while release branches are created on top of `develop` or the currently checked out branch.
Hotfixes are used to quickly push out a change to the production branch. Common examples of hotfixes are fixing typos, and bugs that need to be pushed out as soon as possible to production.

**Comment by Narrev** [comment]
Support

**Comment by devSparkle** [comment]
@Narrev I'll set it up then.
