### ISSUE TITLE
Ensure compatibility with older modules

### ISSUE THREAD

**Issue by devSparkle** [NevermoreFramework/Nevermore#3]
It's important we take some time to verify the integrity and compatibility of the current version of Nevermore against modules designed for prior versions of Nevermore, such as the one hosted by [Quenty](https://github.com/Quenty)/[**NevermoreEngine**](https://github.com/Quenty/NevermoreEngine).

**Comment by Narrev** [comment]
What do you mean?

**Comment by Narrev** [comment]
I think we're good on this one.
