### ISSUE TITLE
The plugin is not loading; it is loading infinitely.

### ISSUE THREAD

**Issue by FunctionalMetatable** [NevermoreFramework/Nevermore#39]

**Comment by AlessandroG200** [comment]
Can confirm this issue. The plugin seems to be loading for an endless amount of time.

What I tried:

- Restarting studio
- Restarting my computer
- Wiping my %temp% folder.
- Reinstalling the plugin.
- Reinstalling studio.

Note: When I reinstalled the plugin, I **don't get any requests** for HTTP access.

I have the latest version of RoStrap as of July 16th
Roblox Studio version: 0.440.0.408152 (64 bit)

Edit: Forgot to mention that no errors are showing up on the console, maybe there is something that is causing RoStrap to hang indefinitely?

**Comment by redJuli21** [comment]
It's also happening to me, I just discovered this plugin and was very excited to use it but it just doesn't finishes loading.

**Comment by FunctionalMetatable** [comment]
This has not been touched for 16 days. I left my computer with RoStrap loading for around 10 minutes and still didn't work. @Validark will this get patched?
@MonsterzSlayerzX65 and @TotallyNotInUse I tried editing as a local plugin and it never worked, some code is kind of in comments so I am thinking its the commented code. Says its in a "state of transition"?? I'm going to start working on a Module Manager for myself if this shouldn't work before August 1st.
EDIT: Why is this last edited on March 7

**Comment by AlessandroG200** [comment]
I think that the last update broke it (as it's not HTTP related). Most likely a something is causing RoStrap to hang. 

Too bad that Roblox doesn't let us use older versions of plugins.

**Comment by redJuli21** [comment]
Validark already said in the discord that he is working on a fix.

**Comment by FunctionalMetatable** [comment]
People are noticing it now on the plugin page @Validark

**Comment by AlessandroG200** [comment]
Any news on this? It's been **_2 months_** since this was reported.

**Comment by FunctionalMetatable** [comment]
**3 months and still not finished yet?**

**Comment by redJuli21** [comment]
> **3 months and still not finished yet?**

Nope. Still not finished I decided to use the files from the demo place and it works.

**Comment by AlessandroG200** [comment]
In my case I opted for a manual update with rojo.

**Comment by FunctionalMetatable** [comment]
Only viable answers up there    /\
                                                /    \
                                              /        \
                                                   |
                                                   |
                                                   |

Closing this issue now. Hope there is a fix soon.
@Validark @TotallyNotInUse @MonsterzSlayerzX65 Closing this issue now.

**Comment by intergrav** [comment]
@TeamDAB-Official Try this:
https://www.roblox.com/library/5454792841/RoStrap-Package-Manager-Offline
Its a offline version made since Roblox security patches broke this original plugin.

**Comment by DaanBiesterbos** [comment]
Why was this closed? The issue still exists...

**Comment by GalacticInspired** [comment]
Can confirm

**Comment by GalacticInspired** [comment]
> @TeamDAB-Official Try this:
> https://www.roblox.com/library/5454792841/RoStrap-Package-Manager-Offline
> Its a offline version made since Roblox security patches broke this original plugin.

not working :(

**Comment by AlessandroG200** [comment]
@GalacticInspired The plugin hasn't been updated in over a year now, so I don't think a fix will come out. The offline version is also broken (see the comments on the plugin page).

**Comment by GalacticInspired** [comment]
Welp this is the end of RoStrap, tho I did find a working plugin for it.

**Comment by GalacticInspired** [comment]
How do I use RoStrap exactly? Interesting in the effects

**Comment by Validark** [comment]
RoStrap now loads properly and *works*! We'll see about a more modern update coming down the pipeline soon. Sorry for the long wait, but feel free to use the updated plugin!

**Comment by GalacticInspired** [comment]
ROSTRAP IS BACK?

**Comment by redJuli21** [comment]
2 years later and rostrap has been fixed. Never thought this day would come

**Comment by AlessandroG200** [comment]
Totally forgot about this, but glad to see RoStrap back in action after 2 years.
